services:

    becklyn.search.indexer:
        class: Becklyn\SearchBundle\Search\SearchIndexer
        arguments:
            - '@becklyn.search.elasticsearch'
            - '@becklyn.search.metadata'


    becklyn.search.command.index:
        class: Becklyn\SearchBundle\Command\IndexCommand
        arguments:
            - '@becklyn.search.metadata'
            - '@becklyn.search.metadata.generator'
            - '@kernel'
            - '@becklyn.search.index.mapping'
            - '@becklyn.search.indexer'
            - '@becklyn.search.entity_loader'
            - '@doctrine'
        tags:
            - { name: console.command }

    # ------------------------------------------------------------------------------------------------------------------------
    # Elasticsearch client
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.elasticsearch:
        class: Becklyn\SearchBundle\Elasticsearch\ElasticsearchClient
        arguments:
            - ~ # set via configuration
            - ~ # set via configuration
            - '@becklyn.search.metadata'
        public: false


    # ------------------------------------------------------------------------------------------------------------------------
    # Index
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.index.mapping:
        class: Becklyn\SearchBundle\Index\IndexMapping
        arguments:
            - '@becklyn.search.elasticsearch'
            - '@becklyn.search.metadata'
            - '@becklyn.search.index.configuration.analysis'
            - '@becklyn.search.index.configuration.language'


    becklyn.search.index.configuration.analysis:
        class: Becklyn\SearchBundle\Index\Configuration\AnalysisConfiguration
        arguments:
            - [] # set via configuration
            - [] # set via configuration
        public: false

    becklyn.search.index.configuration.language:
        class: Becklyn\SearchBundle\Index\Configuration\LanguageConfiguration
        arguments:
            - ~  # set via configuration
            - [] # set via configuration
            - [] # set via configuration
        public: false


    # ------------------------------------------------------------------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.metadata:
        class: Becklyn\SearchBundle\Metadata\Metadata
        arguments:
            - '@cache.system'

    becklyn.search.metadata.generator:
        class: Becklyn\SearchBundle\Metadata\MetadataGenerator
        arguments:
            - '@becklyn.search.language.class_finder'
            - '@becklyn.search.metadata.extractor.class'
            - '@becklyn.search.metadata'

    becklyn.search.metadata.extractor.class:
        class: Becklyn\SearchBundle\Metadata\Extractor\ClassMetadataExtractor
        arguments:
            - '@becklyn.search.language.property_collector'
            - '@cache.app'
        public: false



    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Language integration
    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.search.language.class_finder:
        class: Becklyn\SearchBundle\LanguageIntegration\ClassFinder
        public: false

    becklyn.search.language.property_collector:
        class: Becklyn\SearchBundle\LanguageIntegration\AccessiblePropertyCollector
        public: false



    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Entity loader
    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.search.entity_loader:
        class: Becklyn\SearchBundle\Loader\EntityLoader
        arguments:
            - '@doctrine'
            - '@service_container'
