services:

    # ------------------------------------------------------------------------------------------------------------------------
    # Elasticsearch client
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.elasticsearch:
        class: Becklyn\SearchBundle\Elasticsearch\ElasticsearchClient
        arguments:
            - ~ # set via configuration
            - ~ # set via configuration
            - '@becklyn.search.metadata'
        public: false


    # ------------------------------------------------------------------------------------------------------------------------
    # Index
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.index.mapping:
        class: Becklyn\SearchBundle\Index\IndexMapping
        arguments:
            - '@becklyn.search.elasticsearch'


    becklyn.search.index.configuration.analysis:
        class: Becklyn\SearchBundle\Index\Configuration\AnalysisConfiguration
        arguments:
            - [] # set via configuration
            - [] # set via configuration
        public: false

    becklyn.search.index.configuration.language:
        class: Becklyn\SearchBundle\Metadata\Configuration\LanguageConfiguration
        arguments:
            - ~  # set via configuration
            - [] # set via configuration
        public: false


    # ------------------------------------------------------------------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.metadata:
        class: Becklyn\SearchBundle\Metadata\Metadata
        arguments:
            - '@cache.system'

    becklyn.search.metadata.generator:
        class: Becklyn\SearchBundle\Metadata\MetadataGenerator
        arguments:
            - '@becklyn.search.language.class_finder'
            - '@becklyn.search.metadata.extractor.class'
            - '@becklyn.search.metadata'

    becklyn.search.metadata.extractor.class:
        class: Becklyn\SearchBundle\Metadata\Extractor\ClassMetadataExtractor
        arguments:
            - '@becklyn.search.language.property_collector'
            - '@cache.app'
        public: false



    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Language integration
    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.search.language.class_finder:
        class: Becklyn\SearchBundle\LanguageIntegration\ClassFinder
        public: false

    becklyn.search.language.property_collector:
        class: Becklyn\SearchBundle\LanguageIntegration\AccessiblePropertyCollector
        public: false
