services:

    becklyn.search.client:
        class: Becklyn\SearchBundle\Search\SearchClient
        arguments:
            - '@becklyn.search.elasticsearch'
            - '@becklyn.search.metadata'
            - '@becklyn.search.entity_loader'
            - '@becklyn.search.index.configuration.language'

    becklyn.search.indexer:
        class: Becklyn\SearchBundle\Search\SearchIndexer
        arguments:
            - '@becklyn.search.elasticsearch'
            - '@becklyn.search.metadata'
            - '@becklyn.search.index.configuration.language'
            - '@becklyn.search.accessor.entity_value'
            - '@event_dispatcher'


    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Accessor
    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.search.accessor.entity_value:
        class: Becklyn\SearchBundle\Accessor\EntityValueAccessor
        arguments:
            - '@service_container'
            - [] # set via configuration
        public: false


    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Commands
    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.search.command.index:
        class: Becklyn\SearchBundle\Command\IndexCommand
        arguments:
            - '@becklyn.search.metadata'
            - '@becklyn.search.metadata.generator'
            - '@kernel'
            - '@becklyn.search.index.mapping'
            - '@becklyn.search.indexer'
            - '@becklyn.search.entity_loader'
            - '@doctrine'
        tags:
            - { name: console.command }

    becklyn.search.command.metadata:
        class: Becklyn\SearchBundle\Command\MetadataCommand
        arguments:
            - '@becklyn.search.metadata'
            - '@becklyn.search.metadata.generator'
            - '@kernel'
        tags:
            - { name: console.command }

    becklyn.search.command.debug:
        class: Becklyn\SearchBundle\Command\DebugCommand
        arguments:
            - '@becklyn.search.elasticsearch'
        tags:
            - { name: console.command }


    # ------------------------------------------------------------------------------------------------------------------------
    # Doctrine integration
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.doctrine.event_subscriber:
       class: Becklyn\SearchBundle\Doctrine\DoctrineListener
       arguments:
           - '@becklyn.search.metadata'
           - '@becklyn.search.indexer'
       tags:
           - { name: doctrine.event_subscriber }
       public: false


    # ------------------------------------------------------------------------------------------------------------------------
    # Elasticsearch client
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.elasticsearch:
        class: Becklyn\SearchBundle\Elasticsearch\ElasticsearchClient
        arguments:
            - '@becklyn.search.api.client_factory'
            - ~ # set via configuration
            - ~ # set via configuration
            - '@becklyn.search.metadata'
        public: false

    becklyn.search.api.client_factory:
        class: Becklyn\SearchBundle\Elasticsearch\ElasticsearchApiFactory
        public: false


    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Entity loader
    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.search.entity_loader:
        class: Becklyn\SearchBundle\Loader\EntityLoader
        arguments:
            - '@doctrine'
            - '@service_container'
        public: false


    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Format Processor
    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.search.format_processor.no_op:
        class: Becklyn\SearchBundle\FormatProcessor\NoOpProcessor

    # ------------------------------------------------------------------------------------------------------------------------
    # Index
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.index.mapping:
        class: Becklyn\SearchBundle\Index\IndexMapping
        arguments:
            - '@becklyn.search.elasticsearch'
            - '@becklyn.search.metadata'
            - '@becklyn.search.index.configuration.analysis'
            - '@becklyn.search.index.configuration.language'
        public: false


    becklyn.search.index.configuration.analysis:
        class: Becklyn\SearchBundle\Index\Configuration\AnalysisConfiguration
        arguments:
            - [] # set via configuration
            - [] # set via configuration
        public: false

    becklyn.search.index.configuration.language:
        class: Becklyn\SearchBundle\Index\Configuration\LanguageConfiguration
        arguments:
            - ~  # set via configuration
            - [] # set via configuration
            - [] # set via configuration
        public: false


    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    # Language integration
    # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    becklyn.search.language.class_finder:
        class: Becklyn\SearchBundle\LanguageIntegration\ClassFinder
        public: false

    becklyn.search.language.property_collector:
        class: Becklyn\SearchBundle\LanguageIntegration\AccessiblePropertyCollector
        public: false


    # ------------------------------------------------------------------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------------------------------------------------------------------
    becklyn.search.metadata:
        class: Becklyn\SearchBundle\Metadata\Metadata
        arguments:
            - '@cache.system'
        public: false

    becklyn.search.metadata.factory:
        class: Becklyn\SearchBundle\Metadata\MetadataFactory
        arguments:
            - '@becklyn.search.metadata'
            - '@becklyn.search.metadata.generator'
            - '@kernel'
            - '@logger'
        public: false

    becklyn.search.metadata.generator:
        class: Becklyn\SearchBundle\Metadata\MetadataGenerator
        arguments:
            - '@becklyn.search.language.class_finder'
            - '@becklyn.search.metadata.extractor.class'
            - '@becklyn.search.metadata'
        public: false

    becklyn.search.metadata.extractor.class:
        class: Becklyn\SearchBundle\Metadata\Extractor\ClassMetadataExtractor
        arguments:
            - '@becklyn.search.language.property_collector'
            - '@cache.app'
        public: false
